"""Evidence preservation and chain of custody.

A report describing what a tool found is not evidence. It is a summary of
evidence that no longer exists, because the web changed the moment after you
looked.

The central point, which most investigative tooling gets wrong: **live web
findings are not reproducible.** You cannot re-run a query in 2028 and get 2026's
answer, and any "reproducible steps" section that implies otherwise is
misleading. What survives is the *preserved response body* captured at a known
time with a verifiable hash. The steps explain how the conclusion was reached;
the capture is what proves the input existed.

So this module records four things per fetch:

1. The exact request (URL, method, headers sent, timestamp in UTC)
2. The exact response (status, headers, body) written to disk unmodified
3. A SHA-256 over the raw body, and a manifest hash chaining every capture
4. Who or what performed it, under which case authorization

Plus the thing analysts forget: **negative results**. "We queried Companies
House for this name on this date and it returned nothing" is evidentially
meaningful and is unrecoverable later.

## On admissibility

This module produces the technical substrate. It does not make anything
admissible, and nothing here is legal advice.

In US federal practice the relevant rules are FRE 901(b)(9) (evidence describing
a process or system, showing it produces an accurate result) and FRE 902(13)–(14)
(self-authenticating certified records generated by an electronic process, and
certified data copied from an electronic device, each requiring a certification
from a qualified person). ``declaration_template()`` emits a skeleton for that
certification. Other jurisdictions differ substantially — England and Wales,
India's certificate regime for electronic records (Bharatiya Sakshya
Adhiniyam 2023, s.63 -- formerly Evidence Act s.65B), and EU member states
each impose
different requirements. Counsel decides what is needed; this gives them
something to work with.

One caution worth stating plainly: the confidence scores this toolkit produces
are opinion, not observation. Offering them in proceedings likely engages expert
evidence standards (FRE 702 / Daubert in the US), and the calibration gap
documented in METHOD.md §7 is directly relevant to whether they would survive
that scrutiny. Present captures as fact and scores as analysis, and do not let a
report blur the two.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import platform
import socket
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .scope import CaseScope


def _disclosed_hostname() -> str:
    """Workstation hostname, only if explicitly disclosed.

    Evidence packages are built to be shared, and the manifest recorded the
    local hostname and $USER by default. That is useful for internal chain of
    custody and a privacy leak everywhere else, in a system that otherwise
    emphasises minimisation.

    Opt in with EAE_DISCLOSE_HOST=1 when the package stays internal.
    """

    if os.environ.get("EAE_DISCLOSE_HOST") not in ("1", "true", "yes"):
        return "(not disclosed)"
    return socket.gethostname()


def _disclosed_operator() -> str:
    """Operator identity. Declared, not inferred from $USER."""

    return os.environ.get("EAE_OPERATOR") or "(not disclosed)"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


#: Top-level manifest fields bound by the envelope digest. Listed explicitly
#: rather than "everything except the digest", so adding a field is a decision
#: someone makes rather than a silent widening.
ENVELOPE_FIELDS = (
    "schema", "case_ref", "authorization", "opened_at", "closed_at",
    "capture_count", "manifest_hash", "environment", "fetch_policy",
    "outcomes", "notice", "retention_expiry",
)


def envelope_digest_of(doc: dict) -> str:
    """Canonical digest over ENVELOPE_FIELDS. Same function for writer and
    verifier, so the two cannot drift."""
    import json as _json

    payload = {
        "envelope_schema": doc.get("envelope_schema", "manifest/1"),
        **{k: doc.get(k) for k in ENVELOPE_FIELDS},
    }
    return hashlib.sha256(
        _json.dumps(payload, sort_keys=True, separators=(",", ":"),
                    default=str).encode()).hexdigest()


#: Case material is sensitive by the project's own documentation, so it is not
#: written at whatever the ambient umask happens to be. An empirical probe
#: found 0755 directories and 0644 files: on a shared host or CI runner, any
#: local user could read captured content, investigation URLs and case
#: metadata.
SECURE_DIR_MODE = 0o700
SECURE_FILE_MODE = 0o600


def secure_mkdir(path) -> None:
    """Create a directory 0700, and tighten it if it already exists."""
    from pathlib import Path as _P

    p = _P(path)
    p.mkdir(parents=True, exist_ok=True, mode=SECURE_DIR_MODE)
    # Tighten an existing directory too: mode= only applies at creation, and a
    # pre-existing 0755 output directory is exactly the shared-host case.
    with contextlib.suppress(OSError):
        p.chmod(SECURE_DIR_MODE)


def secure_write(path, data) -> None:
    """Write a file 0600, creating parents 0700.

    The mode is applied before the content: creating world-readable and then
    tightening leaves a window in which the data is exposed.
    """
    import os
    from pathlib import Path as _P

    p = _P(path)
    secure_mkdir(p.parent)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    fd = os.open(p, flags, SECURE_FILE_MODE)
    try:
        with os.fdopen(fd, "wb" if isinstance(data, bytes) else "w") as fh:
            fh.write(data)
    finally:
        with contextlib.suppress(OSError):
            p.chmod(SECURE_FILE_MODE)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# --------------------------------------------------------------------------- #
# Captures
# --------------------------------------------------------------------------- #

@dataclass
class Capture:
    """One request/response pair, preserved."""

    url: str
    method: str
    requested_at: datetime
    status: int | None
    body_sha256: str
    body_bytes: int
    body_path: str
    request_headers: dict[str, str] = field(default_factory=dict)
    response_headers: dict[str, str] = field(default_factory=dict)
    collector: str = ""
    outcome: str = "success"          # success | empty | error | refused
    note: str = ""
    #: Which vantage point served this capture. Part of the hashed envelope
    #: because a capture attributed to the wrong exit is a false record.
    egress: str = ""
    sequence: int = 0
    prev_hash: str = ""
    entry_hash: str = ""

    #: Bumped whenever the hashed field set changes, so a package produced by
    #: an older version cannot be silently verified under newer rules.
    ENTRY_SCHEMA = "capture/2"

    def compute_entry_hash(self) -> str:
        """Hash every integrity-relevant field, not only body identity.

        Version 1 hashed sequence, URL, method, timestamp, status, body digest
        and previous hash. It did **not** hash request headers, response
        headers, collector, note or body_path -- so it was possible to rewrite
        all four on a real package and have the standalone verifier report
        PASSED. "Verified" did not mean the provenance was unaltered, which is
        the one thing an evidence package exists to establish.

        The envelope is versioned and sorted so a future field cannot fall
        outside it by omission: adding a field without bumping ENTRY_SCHEMA
        changes the digest of every capture and fails loudly.
        """
        envelope = {
            "schema": self.ENTRY_SCHEMA,
            "sequence": self.sequence,
            "url": self.url,
            "method": self.method,
            "requested_at": self.requested_at.isoformat(),
            "status": self.status,
            "body_sha256": self.body_sha256,
            "body_bytes": self.body_bytes,
            "body_path": self.body_path,
            "collector": self.collector,
            "outcome": getattr(self.outcome, "value", str(self.outcome)),
            "note": self.note,
            "request_headers": dict(sorted((self.request_headers or {}).items())),
            "response_headers": dict(sorted((self.response_headers or {}).items())),
            "egress": self.egress,
            "prev_hash": self.prev_hash,
        }
        payload = json.dumps(envelope, sort_keys=True, separators=(",", ":"),
                             default=str)
        return hashlib.sha256(payload.encode()).hexdigest()

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["requested_at"] = self.requested_at.isoformat()
        return d


class EvidenceLog:
    """Append-only capture log with a hash chain and a manifest.

    Usage sits alongside the fetcher rather than inside it, so a collector that
    forgets to record is visibly missing from the manifest rather than silently
    unrecorded.
    """

    def __init__(self, scope: CaseScope, root: Path) -> None:
        self.scope = scope
        self.root = Path(root)
        self.bodies = self.root / "captures"
        self.bodies.mkdir(parents=True, exist_ok=True)
        self.captures: list[Capture] = []
        self.opened_at = _utcnow()
        self._last_hash = ""
        #: Populated by the caller from PolicyEngine.summary(). Recorded so the
        #: package can state what the collection policy was, not merely what it
        #: collected.
        self.fetch_policy: dict | None = None

    # ---- recording -------------------------------------------------------- #

    def record(
        self,
        url: str,
        status: int | None,
        body: bytes | str | None,
        *,
        method: str = "GET",
        request_headers: dict[str, str] | None = None,
        response_headers: dict[str, str] | None = None,
        collector: str = "",
        outcome: str | None = None,
        note: str = "",
        requested_at: datetime | None = None,
        egress: str = "",
    ) -> Capture:
        raw = b"" if body is None else (body.encode() if isinstance(body, str) else body)
        digest = sha256_bytes(raw)
        seq = len(self.captures) + 1

        # Content-addressed: identical bodies stored once, and the filename is
        # itself verifiable against the hash in the manifest.
        path = self.bodies / f"{digest}.bin"
        if not path.exists():
            secure_write(path, raw)

        if outcome is None:
            if status is None or status >= 400:
                outcome = "error"
            elif not raw:
                outcome = "empty"
            else:
                outcome = "success"

        cap = Capture(
            url=url,
            method=method,
            requested_at=requested_at or _utcnow(),
            status=status,
            body_sha256=digest,
            body_bytes=len(raw),
            body_path=str(path.relative_to(self.root)),
            request_headers=dict(request_headers or {}),
            response_headers=dict(response_headers or {}),
            collector=collector,
            outcome=outcome,
            note=note,
            sequence=seq,
            prev_hash=self._last_hash,
            egress=egress,
        )
        cap.entry_hash = cap.compute_entry_hash()
        self._last_hash = cap.entry_hash
        self.captures.append(cap)
        return cap

    def record_negative(
        self, url: str, collector: str, note: str, *, status: int | None = 200
    ) -> Capture:
        """A query that ran and returned nothing.

        Evidentially meaningful and unrecoverable later. "We searched the
        register on this date and it held no matching entity" is a finding.
        """
        return self.record(url, status, b"", collector=collector,
                           outcome="empty", note=note)

    def record_refusal(self, target: str, collector: str, reason: str) -> Capture:
        """A source deliberately not queried.

        Recording what you chose not to do matters as much as what you did --
        it is the difference between a scoped investigation and one that simply
        failed to find something.
        """
        return self.record(target, None, b"", collector=collector,
                           outcome="refused", note=reason)

    # ---- verification ------------------------------------------------------ #

    def _safe_body_path(self, body_path: str) -> Path | None:
        """Resolve a manifest body_path, refusing anything outside the package.

        When verifying a package you did not create, the manifest is untrusted
        input and ``body_path`` is a file-read primitive: "../../../etc/shadow"
        resolves happily under a naive join.
        """
        candidate = (self.root / body_path).resolve()
        try:
            candidate.relative_to(self.root.resolve())
        except ValueError:
            return None
        return candidate

    def verify(self) -> tuple[bool, list[str]]:
        """Re-check every body hash and the full chain."""
        problems: list[str] = []
        prev = ""
        for cap in self.captures:
            p = self._safe_body_path(cap.body_path)
            if p is None:
                problems.append(
                    f"seq {cap.sequence}: body_path escapes the package "
                    f"({cap.body_path}) — the manifest is malformed or hostile")
                prev = cap.entry_hash
                continue
            if not p.exists():
                problems.append(f"seq {cap.sequence}: body missing ({cap.body_path})")
            elif sha256_bytes(p.read_bytes()) != cap.body_sha256:
                problems.append(f"seq {cap.sequence}: body hash mismatch")
            if cap.prev_hash != prev:
                problems.append(f"seq {cap.sequence}: chain break")
            if cap.compute_entry_hash() != cap.entry_hash:
                problems.append(f"seq {cap.sequence}: entry hash mismatch")
            prev = cap.entry_hash
        return (not problems), problems

    # ---- output ------------------------------------------------------------ #

    @property
    def manifest_hash(self) -> str:
        """The capture-chain head.

        Retained under its existing name so older packages still parse, but it
        is NOT the package digest: it commits only to the capture chain. See
        ``envelope_hash``.
        """
        return self._last_hash or sha256_bytes(b"")

    #: Bumped when the envelope's field set changes, so a package written by an
    #: older version cannot be silently verified under newer rules.
    ENVELOPE_SCHEMA = "manifest/1"

    def envelope_digest(self, doc: dict) -> str:
        """Digest over the top-level manifest metadata AND the chain head.

        The chain protects the captures. Nothing protected the manifest's own
        assertions, so editing ``case_ref``, ``authorization``,
        ``fetch_policy`` and ``environment.tool_version`` on a valid package
        and the official verifier still returned ok, reporting the forged case
        reference back.

        For an evidence-preservation tool those are the load-bearing claims:
        under what authority the collection happened, under what policy, and
        with which build. A verifier that authenticates the bytes but not the
        circumstances authenticates the wrong thing.
        """
        return envelope_digest_of(doc)

    def environment(self) -> dict[str, str]:
        from . import __version__
        return {
            "tool": "attribution-graph",
            "tool_version": __version__,
            "python": platform.python_version(),
            "platform": platform.platform(),
            "hostname": _disclosed_hostname(),
            "operator": _disclosed_operator(),
        }

    def write_manifest(self) -> Path:
        ok, problems = self.verify()
        doc = {
            "case_ref": self.scope.case_ref,
            "authorization": self.scope.authorization,
            "opened_at": self.opened_at.isoformat(),
            "closed_at": _utcnow().isoformat(),
            "environment": self.environment(),
            "capture_count": len(self.captures),
            "outcomes": {
                o: sum(1 for c in self.captures if c.outcome == o)
                for o in ("success", "empty", "error", "refused")
            },
            "fetch_policy": self.fetch_policy or {
                "robots_policy": self.scope.robots_policy,
                "statement": "Policy declared in the case file; per-URL "
                             "evaluation was not recorded for this run.",
            },
            "manifest_hash": self.manifest_hash,
            "self_verified": ok,
            "verification_problems": problems,
            "captures": [c.to_dict() for c in self.captures],
            "notice": (
                "Live web findings are not reproducible. Re-running these requests "
                "at a later date will not return the same content. The preserved "
                "bodies under captures/ are the evidentiary artifact; this manifest "
                "attests to what was retrieved, when, and that it is unaltered."
            ),
        }
        # Bind the top-level assertions. Without this, the chain authenticated
        # the captures while case_ref, authorization, fetch_policy and the tool
        # version could be rewritten freely and still verify.
        doc["envelope_schema"] = self.ENVELOPE_SCHEMA
        doc["envelope_digest"] = envelope_digest_of(doc)

        path = self.root / "evidence_manifest.json"
        secure_write(path, json.dumps(doc, indent=2, default=str))
        return path

    def write_timestamp_request(self) -> Path:
        """RFC 3161 timestamp request over the manifest hash.

        A hash chain proves internal consistency but not *when* it was made --
        the operator controls the clock. A trusted timestamp from a third-party
        TSA closes that gap and is what turns "we say we captured this in
        August" into something independently checkable.

            openssl ts -query -data evidence_manifest.json -sha256 -cert \\
                -out request.tsq
            curl -H "Content-Type: application/timestamp-query" \\
                --data-binary @request.tsq <TSA_URL> -o response.tsr
            openssl ts -verify -data evidence_manifest.json \\
                -in response.tsr -CAfile tsa-ca.pem
        """
        path = self.root / "TIMESTAMP.md"
        secure_write(path,
            "# Trusted timestamping\n\n"
            f"Manifest hash (SHA-256 chain head): `{self.manifest_hash}`\n\n"
            "The hash chain proves the capture set is internally consistent and "
            "unaltered. It does not prove *when* it was created, because the "
            "operator controls the system clock. Obtain an RFC 3161 timestamp "
            "from a trusted authority to close that gap:\n\n"
            "```bash\n"
            "openssl ts -query -data evidence_manifest.json -sha256 -cert -out request.tsq\n"
            "curl -H \"Content-Type: application/timestamp-query\" \\\n"
            "     --data-binary @request.tsq <TSA_URL> -o response.tsr\n"
            "openssl ts -verify -data evidence_manifest.json -in response.tsr \\\n"
            "     -CAfile tsa-ca.pem\n"
            "```\n\n"
            "Store `response.tsr` alongside the manifest. Do this at capture "
            "time; a timestamp obtained months later proves only that the file "
            "existed by then.\n"
        )
        return path


# --------------------------------------------------------------------------- #
# Declaration
# --------------------------------------------------------------------------- #

def _policy_sentence(log: EvidenceLog) -> str:
    fp = log.fetch_policy or {}
    stated = fp.get("statement")
    if stated:
        return stated
    p = log.scope.robots_policy
    return {
        "respect": "Automated retrieval was limited to paths not disallowed by "
                   "each host's robots.txt.",
        "record": "robots.txt directives were recorded against each capture. "
                  "Retrieval was not limited by them.",
        "ignore": "robots.txt was not consulted during collection.",
    }.get(p, f"Collection policy declared as '{p}'.")


def declaration_template(log: EvidenceLog, findings_summary: str = "") -> str:
    """Skeleton certification for the person who ran the collection.

    Not legal advice and not a finished document. It records the facts a
    qualified-person certification generally needs -- what system, run by whom,
    when, producing what, and how integrity is checked -- so counsel is editing
    rather than starting from nothing.
    """
    env = log.environment()
    ok, problems = log.verify()
    counts = {o: sum(1 for c in log.captures if c.outcome == o)
              for o in ("success", "empty", "error", "refused")}

    return f"""# Declaration regarding automated evidence collection

**DRAFT — for review by counsel. Not legal advice. Jurisdiction-specific
requirements vary; in US federal practice see FRE 901(b)(9) and 902(13)–(14),
in England and Wales the relevant practice directions, and in India the
certificate regime for electronic records under the Bharatiya Sakshya Adhiniyam 2023, s.63
(which replaced Evidence Act s.65B on 1 July 2024).**

This package produces material a certificate can describe. It does not itself
constitute compliance with any jurisdiction's evidentiary rules, and nothing
here is legal advice.

---

I, ________________________ [name], declare as follows:

**1. Qualification.** I am ________________________ [role, employer]. I am
familiar with the operation of the system described below and am qualified to
certify the matters stated here. [State relevant experience and the basis of
familiarity with this system.]

**2. Authorization.** This collection was performed under case reference
`{log.scope.case_ref}`, pursuant to: {log.scope.authorization}

**3. System.** Collection was performed using {env['tool']} version
{env['tool_version']}, an automated open-source tool that issues HTTP requests
to publicly accessible internet resources and records the responses without
modification. Source code for the version used is publicly available and its
behaviour can be independently inspected.

**4. Environment.**
- Platform: {env['platform']}
- Python runtime: {env['python']}
- Host: {env['hostname']}
- Operator account: {env['operator']}

**5. Collection period.** Requests were issued between
{log.opened_at.isoformat()} and {_utcnow().isoformat()} (UTC).

**6. Scope of collection.** {len(log.captures)} requests were recorded:
{counts['success']} returning content, {counts['empty']} returning no matching
records, {counts['error']} returning errors, and {counts['refused']} sources
deliberately not queried (reasons recorded in the manifest).

**6a. Collection policy.** {_policy_sentence(log)}

**7. Preservation.** Each response body was written to storage unmodified and
identified by the SHA-256 digest of its contents. Each manifest entry
incorporates the hash of the preceding entry, so that removal, alteration or
reordering of any capture invalidates every subsequent entry.

**8. Integrity.** Manifest chain head: `{log.manifest_hash}`

Verification at time of writing: {"PASSED" if ok else "FAILED — " + "; ".join(problems)}

Integrity may be independently re-verified by re-hashing each file under
`captures/` and comparing to `evidence_manifest.json`.

**9. Non-reproducibility.** The resources queried are live internet resources
whose content changes over time. Re-issuing these requests at a later date will
not necessarily return the same content. The preserved response bodies are the
record of what those resources contained at the times stated; they are not
reproducible by re-execution, and I do not represent that they are.

**10. Analysis distinguished from observation.** The preserved captures are a
record of what was retrieved. Any confidence scores, entity groupings or
attribution conclusions accompanying them are analytical opinion derived from
those captures by a documented statistical method, and are offered as such.
[If analytical conclusions are being offered, counsel should consider whether
expert evidence requirements apply.]

**11. Findings.** {findings_summary or "[Summary of findings, if this declaration covers them.]"}

---

I declare under penalty of perjury under the laws of ______________ that the
foregoing is true and correct to the best of my knowledge.

Executed on __________________ at __________________.

Signature: ________________________
Printed name: ________________________
"""


def write_evidence_package(
    log: EvidenceLog, findings_summary: str = "", capturer: object | None = None
) -> list[Path]:
    """Manifest, timestamping instructions, declaration draft, verifier.

    ``capturer`` is an optional ``ScreenshotCapturer``. Screenshots are derived
    renderings, so they get their own manifest and text log rather than being
    mixed into the wire-capture manifest -- a consumer must not be able to
    mistake a browser rendering for the bytes that were served.
    """
    paths = [log.write_manifest(), log.write_timestamp_request()]

    if capturer is not None and getattr(capturer, "shots", None):
        capturer.export_json(log.root / "screenshot_manifest.json")
        capturer.export_text(log.root / "SCREENSHOT_LOG.txt")
        paths += [log.root / "screenshot_manifest.json",
                  log.root / "SCREENSHOT_LOG.txt"]

    d = log.root / "DECLARATION_DRAFT.md"
    d.write_text(declaration_template(log, findings_summary))
    paths.append(d)

    v = log.root / "verify.py"
    v.write_text('''#!/usr/bin/env python3
"""Standalone integrity verifier. No dependencies; runs anywhere.

Deliberately self-contained so a third party can check the package without
installing the tool that produced it.

    python verify.py
"""
import hashlib
import json
import sys
from pathlib import Path

root = Path(__file__).parent
doc = json.loads((root / "evidence_manifest.json").read_text())

problems, prev = [], ""
root_resolved = root.resolve()
for cap in doc["captures"]:
    # body_path is untrusted when verifying someone else's package.
    p = (root / cap["body_path"]).resolve()
    try:
        p.relative_to(root_resolved)
    except ValueError:
        problems.append(f"seq {cap['sequence']}: body_path escapes the package")
        prev = cap["entry_hash"]
        continue
    if not p.exists():
        problems.append(f"seq {cap['sequence']}: missing {cap['body_path']}")
    elif hashlib.sha256(p.read_bytes()).hexdigest() != cap["body_sha256"]:
        problems.append(f"seq {cap['sequence']}: body hash mismatch")
    if cap["prev_hash"] != prev:
        problems.append(f"seq {cap['sequence']}: chain break")
    payload = json.dumps({
        "schema": cap.get("schema", "capture/2"),
        "sequence": cap["sequence"],
        "url": cap["url"],
        "method": cap.get("method", "GET"),
        "requested_at": cap["requested_at"],
        "status": cap.get("status"),
        "body_sha256": cap.get("body_sha256", ""),
        "body_bytes": cap.get("body_bytes", 0),
        "body_path": cap.get("body_path", ""),
        "collector": cap.get("collector", ""),
        "outcome": cap.get("outcome", "success"),
        "note": cap.get("note", ""),
        "request_headers": dict(sorted((cap.get("request_headers") or {}).items())),
        "response_headers": dict(sorted((cap.get("response_headers") or {}).items())),
        "egress": cap.get("egress", ""),
        "prev_hash": cap.get("prev_hash", ""),
    }, sort_keys=True, separators=(",", ":"))
    if hashlib.sha256(payload.encode()).hexdigest() != cap["entry_hash"]:
        problems.append(f"seq {cap['sequence']}: entry hash mismatch")
    prev = cap["entry_hash"]

# --- manifest envelope ----------------------------------------------------
# The chain covers the captures. This covers the claims the package makes about
# itself: under what authority the collection happened, under what policy, with
# which build. Those are the load-bearing assertions for an evidence package,
# and rewriting `authorization` used to pass this verifier cleanly.
#
# Kept byte-identical in intent to attribution_graph.evidence.envelope_digest_of.
ENVELOPE_FIELDS = (
    "schema", "case_ref", "authorization", "opened_at", "closed_at",
    "capture_count", "manifest_hash", "environment", "fetch_policy",
    "outcomes", "notice", "retention_expiry",
)

declared_envelope = doc.get("envelope_digest")
if declared_envelope is None:
    problems.append(
        "manifest has no envelope_digest: top-level metadata (case_ref, "
        "authorization, fetch_policy, environment) is unauthenticated")
else:
    _env_payload = json.dumps(
        {"envelope_schema": doc.get("envelope_schema", "manifest/1"),
         **{k: doc.get(k) for k in ENVELOPE_FIELDS}},
        sort_keys=True, separators=(",", ":"), default=str)
    if hashlib.sha256(_env_payload.encode()).hexdigest() != declared_envelope:
        problems.append(
            "envelope digest mismatch: the manifest's own metadata has been "
            "altered (case_ref, authorization, opened_at, closed_at, "
            "environment, fetch_policy, outcomes, notice, capture_count or "
            "manifest_hash)")

# --- chain head -----------------------------------------------------------
# A hash chain prevents insertion and reordering in the middle, because later
# entries commit to earlier ones. It does NOT prevent deleting a suffix: the
# remaining entries still link correctly to each other.
#
# A review removed the final capture from a real package, decremented
# capture_count, left manifest_hash untouched, and this verifier reported
# PASSED. Comparing the declared head against the recomputed one closes that.
declared_head = doc.get("manifest_hash", "")
if prev != declared_head:
    problems.append(
        "chain head mismatch: the manifest declares "
        f"{declared_head[:16]}... but the captures recompute to "
        f"{prev[:16] or '(none)'}... -- one or more trailing captures have "
        "been removed, or the manifest was edited")

declared_count = doc.get("capture_count")
if declared_count is not None and declared_count != len(doc["captures"]):
    problems.append(
        f"capture_count says {declared_count} but {len(doc['captures'])} "
        "captures are present")

print(f"case:     {doc['case_ref']}")
print(f"captures: {len(doc['captures'])}")
print(f"chain:    {declared_head}")
if problems:
    print(f"\\nFAILED ({len(problems)} problem(s)):")
    for p in problems:
        print("  " + p)
    sys.exit(1)
print("\\nPASSED - every body matches its digest, every entry hash covers its")
print("full provenance envelope, and the chain head matches the manifest.")
print()
print("Note: this proves internal consistency. It cannot prove the package was")
print("not regenerated wholesale. Only an external anchor -- an RFC 3161")
print("timestamp over the manifest hash, or a signature -- establishes that.")
print("See TIMESTAMP.md.")
''')
    paths.append(v)
    return paths
